# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\marinc\AutonoMouse\Software\schedule-generator\UI\CorrelationGNGNaturalPlumesUI.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1125, 587)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 2, 1, 1)
        self.trialLengthEdit = QtWidgets.QLineEdit(Form)
        self.trialLengthEdit.setObjectName("trialLengthEdit")
        self.gridLayout.addWidget(self.trialLengthEdit, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 4, 1, 1)
        self.onsetEdit = QtWidgets.QLineEdit(Form)
        self.onsetEdit.setObjectName("onsetEdit")
        self.gridLayout.addWidget(self.onsetEdit, 5, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.offsetEdit = QtWidgets.QLineEdit(Form)
        self.offsetEdit.setObjectName("offsetEdit")
        self.gridLayout.addWidget(self.offsetEdit, 5, 3, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 4)
        self.CorrRewardedCheck = QtWidgets.QCheckBox(Form)
        self.CorrRewardedCheck.setText("")
        self.CorrRewardedCheck.setObjectName("CorrRewardedCheck")
        self.gridLayout.addWidget(self.CorrRewardedCheck, 5, 5, 1, 1)
        self.nTrialsEdit = QtWidgets.QLineEdit(Form)
        self.nTrialsEdit.setObjectName("nTrialsEdit")
        self.gridLayout.addWidget(self.nTrialsEdit, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 2, 0, 1, 6)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 3, 1, 1)
        self.CorrPlumesButton = QtWidgets.QPushButton(Form)
        self.CorrPlumesButton.setObjectName("CorrPlumesButton")
        self.gridLayout.addWidget(self.CorrPlumesButton, 7, 0, 1, 1)
        self.lickFractionEdit = QtWidgets.QLineEdit(Form)
        self.lickFractionEdit.setObjectName("lickFractionEdit")
        self.gridLayout.addWidget(self.lickFractionEdit, 5, 4, 1, 1)
        self.CorrPlumesLabel = QtWidgets.QLabel(Form)
        self.CorrPlumesLabel.setObjectName("CorrPlumesLabel")
        self.gridLayout.addWidget(self.CorrPlumesLabel, 7, 1, 1, 1)
        self.UncorrPlumesButton = QtWidgets.QPushButton(Form)
        self.UncorrPlumesButton.setObjectName("UncorrPlumesButton")
        self.gridLayout.addWidget(self.UncorrPlumesButton, 8, 0, 1, 1)
        self.UncorrPlumesLabel = QtWidgets.QLabel(Form)
        self.UncorrPlumesLabel.setObjectName("UncorrPlumesLabel")
        self.gridLayout.addWidget(self.UncorrPlumesLabel, 8, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "Valve Map Setup : 0 = Blank, 1 = Odour 1, 2 = Odour 2, 4 = Blank"))
        self.label_2.setText(_translate("Form", "Trial Onset (s)"))
        self.trialLengthEdit.setText(_translate("Form", "2.0"))
        self.label_6.setText(_translate("Form", "Lick Fraction"))
        self.onsetEdit.setText(_translate("Form", "0.1"))
        self.label_5.setText(_translate("Form", "Trial Length (s)"))
        self.offsetEdit.setText(_translate("Form", "0.1"))
        self.label.setText(_translate("Form", "Number of Trials"))
        self.label_3.setText(_translate("Form", "Correlation GNG Natural Plumes"))
        self.nTrialsEdit.setText(_translate("Form", "300"))
        self.label_7.setText(_translate("Form", "Correlated Rewarded"))
        self.label_4.setText(_translate("Form", "Trial Offset (s)"))
        self.CorrPlumesButton.setText(_translate("Form", "Correlated Plumes"))
        self.lickFractionEdit.setText(_translate("Form", "0.1"))
        self.CorrPlumesLabel.setText(_translate("Form", "-"))
        self.UncorrPlumesButton.setText(_translate("Form", "Uncorrelated Plumes"))
        self.UncorrPlumesLabel.setText(_translate("Form", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

